package com.example.meridian.data.model

import java.time.Instant
import java.time.LocalDate
import java.time.LocalTime
import java.time.ZoneId

/**
 * Meridian Data Model & Schema definitions.
 * Categorized explicitly into:
 * [P] Plaintext - required for query routing, rules, and synchronization
 * [ENC] Encrypted - encrypted on-device with AES-GCM before writing to storage
 */

enum class SyncStatus {
    SAVED,
    SENDING,
    SAVED_OFFLINE,
    OFFLINE
}

data class UserProfile(
    val uid: String, // [P]
    val displayName: String, // [P in header, ENC in detailed profile]
    val avatarEmoji: String = "🌿",
    val homeCity: String = "Pune", // [ENC]
    val timezone: ZoneId = ZoneId.of("Asia/Kolkata"), // [ENC]
    val awakeStart: LocalTime = LocalTime.of(7, 30),
    val awakeEnd: LocalTime = LocalTime.of(23, 0),
    val birthdayMonth: Int = 10,
    val birthdayDay: Int = 14,
    val publicKey: String = "" // [P]
)

data class SpaceFlags(
    val privateOptIn: Map<String, Boolean> = emptyMap(), // [P]
    val streakOptIn: Map<String, Boolean> = emptyMap(), // [P]
    val checkinsOptIn: Map<String, Boolean> = emptyMap(), // [P]
    val revealUpdatesTogether: Boolean = false // [P]
)

data class SpaceInfo(
    val spaceId: String, // [P]
    val members: List<String>, // [P] max 2
    val createdBy: String, // [P]
    val status: String = "active", // [P]
    val flags: SpaceFlags = SpaceFlags(),
    val anniversaryDate: LocalDate = LocalDate.now().minusMonths(14)
)

data class UserPresence(
    val uid: String, // [P]
    val state: String = "Around", // [ENC] Around, Heads down, Asleep
    val note: String = "", // [ENC]
    val updatedAt: Instant = Instant.now()
)

data class QuickPing(
    val id: String,
    val fromUid: String, // [P]
    val kind: String, // [ENC] tap, hug, kiss, miss_you, arrived_safe
    val createdAt: Instant = Instant.now() // [P]
)

data class DailyUpdate(
    val uid: String, // [P]
    val dateKey: String, // [P] YYYY-MM-DD in author's local zone
    val feelings: List<String> = emptyList(), // [ENC] e.g. ["🥰 loved", "😌 calm"]
    val feelingNote: String = "", // [ENC] max 80 chars
    val actions: List<String> = emptyList(), // [ENC] e.g. ["💼 working", "🚶 out and about"]
    val actionNote: String = "", // [ENC] max 80 chars
    val updatedAt: Instant = Instant.now() // [P]
)

data class DailyQuestion(
    val id: String, // [P]
    val deck: String, // [P] light, deep, future, silly, spicy
    val promptText: String
)

data class QuestionAnswer(
    val questionId: String, // [P]
    val uid: String, // [P]
    val answerText: String, // [ENC]
    val reaction: String? = null, // [ENC]
    val createdAt: Instant = Instant.now() // [P]
)

data class Letter(
    val id: String, // [P]
    val fromUid: String, // [P]
    val toUid: String, // [P]
    val kind: String = "text", // [P] text, voice, photo
    val trigger: String, // [P] "I miss you", "can't sleep", "bad day", "scheduled", etc.
    val title: String, // [ENC]
    val body: String, // [ENC]
    val unsealAt: Instant? = null, // [P] null if trigger-based
    val openedAt: Instant? = null, // [P]
    val notifyOnOpen: Boolean = false // [P]
)

data class Occasion(
    val id: String,
    val type: String, // birthday, anniversary, person
    val name: String,
    val month: Int,
    val day: Int,
    val year: Int? = null,
    val forUid: String? = null
)

data class Visit(
    val id: String,
    val place: String,
    val startDate: LocalDate,
    val endDate: LocalDate,
    val notes: String = "",
    val isPast: Boolean = true
) {
    val durationDays: Long
        get() = java.time.temporal.ChronoUnit.DAYS.between(startDate, endDate) + 1
}

data class TimelineItem(
    val id: String,
    val dateStr: String,
    val emoji: String,
    val text: String,
    val category: String = "Milestone",
    val autoGenerated: Boolean = false
)

data class StreakInfo(
    val currentStreak: Int = 18,
    val cumulativeDaysConnected: Int = 312,
    val restDaysAvailable: Int = 2,
    val isOptedIn: Boolean = true
)

data class VaultItem(
    val id: String, // [P]
    val createdBy: String, // [P]
    val title: String, // [ENC]
    val body: String, // [ENC]
    val kind: String = "note", // [P] note, photo, view_once
    val viewOnce: Boolean = false, // [P]
    val hasBeenViewed: Boolean = false, // [P]
    val createdAt: Instant = Instant.now() // [P]
)
